### PR TITLE
Additional gitvote setup!

### PR DESCRIPTION
**Pull request by jeefy**
Add language around voting and update issue template to automatically include the slash-vote command

This PR will also be used to configure the gitvote PR check! Please don't merge, just LGTM :)

### CODE REVIEW

**Comment by caniszczyk** [comment]
@jeefy I like this setup outside of it having be the "toc" team as voters, I think it's better to just list the 11 handles of folks as voters so it's a bit more transparent who is on that list

**Comment by TheFoxAtWork** [comment]
Is it possible to integrate populating handles based on the group automatically so can identify which TOC group/members voted? this is what we currently capture but then sum to ensure quorum and majority.

**Comment by jeefy** [comment]
@TheFoxAtWork I think that's already handled when the vote closes. When a vote closes, it will output a summary including all binding votes. 

See https://github.com/cncf/gitvote/blob/main/docs/screenshots/vote-closed.png 

Is that what you were thinking of?

**Comment by RichiH** [comment]
It's a nit, but the fact that the progress thing next to GitVote keeps spinning make it seem as if the automation is broken.

One downside is that we can't see what happened when. Can GitVote track that and make it visible in this issue?

**Comment by TheFoxAtWork** [comment]
> @TheFoxAtWork I think that's already handled when the vote closes. When a vote closes, it will output a summary including all binding votes.
> 
> See https://github.com/cncf/gitvote/blob/main/docs/screenshots/vote-closed.png
> 
> Is that what you were thinking of?

Yep.

**Comment by jeefy** [comment]
@RichiH Captured your feedback here: https://github.com/cncf/gitvote/issues/162

**Comment by jeefy** [comment]
For the next few sandbox votes, @amye wants to batch and call votes all at once (and timebox them to one week)

Given that, and how easy this PR was, I'm going to close this for now and revisit in the future. ❤️

**Pull request closed without merging**
